### ISSUE TITLE
Feature Request: change Zoom (and other props) dynamically

### ISSUE THREAD

**Issue by seniordev09** [ThibaultJanBeyer/DragSelect#111]
Hi, @ThibaultJanBeyer 
I want to change zoom after created dragSelect. how can do it?

![image](https://user-images.githubusercontent.com/47884397/134311493-d0a5554f-8d55-4eae-8ece-535e27052984.png)

Thanks

**Comment by ThibaultJanBeyer** [comment]
Hi @dev181992 thanks a lot for using the tool <3
Indeed that is unfortunately not feasible, you'd have to create a new instance.
But this would be a good idea in my opinion. Being able to change all properties dynamically as well.
If you want, this addition would be very welcome, otherwise, I'll try to find some time to add this

**Comment by ThibaultJanBeyer** [comment]
This is now possible [see docs](https://github.com/ThibaultJanBeyer/DragSelect#post-initialization-setting-updates):

```JavaScript
ds.setSettings({ zoom: 1000000 })
```
