### ISSUE TITLE
getCursorPositionDifference Reports wrong Difference when clicking on a single Element

### ISSUE THREAD

**Issue by RealTJ** [ThibaultJanBeyer/DragSelect#13]
When i select different Elements, one after another, getCursorPositionDifference does not report a Difference {x:0, y:0}, instead it reports an arbitrary amount. 
You can reproduce the issue locally:

1. Add onSelectElement listener and console.log it's result.
2. Click on Element 1, expected {x:0, y:0} instead got {x: 28.25, y: 35.75}
3. Click on Element 2, expected {x:0, y:0} instead got {x: 91.25, y: 31.75}

Kinda working on it right now, what i thought of is to update newCursorPos, everytime an Element is selected. I will make the pull request later.

**Comment by ThibaultJanBeyer** [comment]
Ay, this is a bit tricky because if should have two different behaviours:

Expected behaviour for drag should be:
```
1 Click: 0, 0
Drag: difference between 1st click and current mouse position.
```

However, I’m not sure about singleclicks, shouldn’t it be:
```
1st click: 0, 0
2nd click: the difference between 2nd click and 1st click
3rd click: the difference between 3rd click and 2nd click
```
right? This makes it quite complex…

Maybe this logic is too complex, I don’t know if there is a usecase were a user would need to record the difference between 2 independent clicks.

My suggestion is to forget about the single clicks for now since it would make it too complex (unless you have an easy solution), and get the resetting to 0,0 on each first click. Your first solution with resetting the `newCursorPos` on each selection was not bad. My biggest concern was just that the user want to have a value at this point that is the last cursor position. So how about having one more property: `lastCursorPos` which is the last recorded position of the curser before the new selection, this could be taken inside the `reset` function?

I would not only update it when an element is selected. A user should also be able to just drag around without selecting anything and still get correct differences.

**Comment by RealTJ** [comment]
I had a use case for the single click (but it is very specific so i do not know if it even applies, i solved it different in the app).

The use case was that i had multiple selectboxes and i wanted an easy way to select multiple selectboxes, which the DragSelect is perfect for, because everyone who uses a computer knows how the selection rectangle works. But i already had a working path for single clicks, so i wanted to deactivate the behavior when a single click is registered (here i would use the old behavior) and only use the new behavior when the selection is being triggered. Now in that use case every time it runs into `onElementSelect` i could detect a single click vs. multi-selection, via getCursorPositionDifference. This is how i wanted to use it, but after our discussion and some thougt this was more of hack than really how this library should work.

Not sure if there are other use cases for distinguishing between selection and single-clicks, but if i (or someone else) needs that functionality in the future, we should look into another implementation than through differences in mouse-clicks.

Now back to your suggestion, it makes sense to me, since now you can see the distance between the start of a new selection and the end of the old selection or the distance/size between the start of the current selection and the current element or the distance/size of the selection in general. I will try to implement it with the `lastCursorPos` as additional parameter.

**Comment by ThibaultJanBeyer** [comment]
Hmm if it’s just about a way to detect whether it’s a drag or a single click, we should address that in another, separate PR. There are already two different handlers in the app `_onClick` for single clicks and a `_startUp` for selections. Would adding a new callback inside the single `_onClick` method to differentiate them do the trick? Could be named `onElementClick`. I think that makes sense too.

**Comment by RealTJ** [comment]
I will look into this issue with `onElementClick` later. I really like working with you on the project, it's really motivating. 

I implemented `lastCursorPos`, but i'm not sure if i'm doing it correctly and need another pair of eyes. I have a separate Branch on my Fork, should i make a PR so you can look/test the functionality?

**Comment by ThibaultJanBeyer** [comment]
And I really like that you are contributing, it’s a great help.
Yes please make a PR so I can check the code 👍
