### ISSUE TITLE
Why it's not selecting items ? showing blank array of items..

### ISSUE THREAD

**Issue by meshv-p** [ThibaultJanBeyer/DragSelect#140]
First this is selecting and showing item then as soon as i release my mouse then it will blank.. How...
How can i get all items?.

Any idea?.

![image](https://user-images.githubusercontent.com/77038149/198520902-ee48abbe-7080-4186-92a8-09eb7b0ec27e.png)

## Here is my code  in react js
![image](https://user-images.githubusercontent.com/77038149/198521193-7ebf420c-d858-413a-9927-b1de27a72294.png)

**Comment by owenfar** [comment]
Hello @meshv-p,

It is very hard to understand the issue with just the screenshots that you provided. Can you please try to replicate the same problem on codepen or similar platform so that we can better evaluate and test it there?

**Comment by meshv-p** [comment]
@owenfar yea, I will provide that sandbox link..

**Comment by ThibaultJanBeyer** [comment]
Hi @meshv-p without code it’s impossible to say for certain. But you mentioned using react. I think in your case it is initiating multiple instances of dragselect because or re-rendering, ideally you would put your code into a `useEffect` method.

I recently created a guide on a good way + example to use it with react, you can find the [DragSelect + React guide here](https://dragselect.com/docs/guided-examples/React).

I’ll close this issue for now. Please try following the guide OR providing a code exmaple, then feel free to re-open if the issue still exists.

**Comment by msueping** [comment]
> Hi @meshv-p without code it’s impossible to say for certain. But you mentioned using react. I think in your case it is initiating multiple instances of dragselect because or re-rendering, ideally you would put your code into a `useEffect` method.
> 
> I recently created a guide on a good way + example to use it with react, you can find the [DragSelect + React guide here](https://dragselect.com/docs/guided-examples/React).
> 
> I’ll close this issue for now. Please try following the guide OR providing a code exmaple, then feel free to re-open if the issue still exists.

I'm trying to follow your React guide and after copying and pasting the code in step 1. "Create a context", I get this typescript error that fails to compile
![image](https://user-images.githubusercontent.com/67658122/210897660-c2755c75-1660-4297-94a7-a6b528eed778.png)
![image](https://user-images.githubusercontent.com/67658122/210898026-cfffe6cc-80ad-456a-9acf-b3f0ef8bfbd4.png)
