### ISSUE TITLE
Feature Request - Allow key to add items on selection

### ISSUE THREAD

**Issue by OmgImAlexis** [ThibaultJanBeyer/dragSelect#2]
It'd be helpful if you could provide a key code that can be held to allow adding more items to the current selection similar to how [jQuery selectable works](https://jqueryui.com/selectable/).

> Enable a DOM element (or group of elements) to be selectable. Draw a box with your cursor to select items. **Hold down the Ctrl key to make multiple non-adjacent selections**.

**Comment by ThibaultJanBeyer** [comment]
So you mean after the first selection, being able to add more items to the selection via a key.
That is a great idea! Which one would be a good pick in your opinion? I see that jQuery uses the CTRL key. Sadly on OSX, the CTRL key is triggering a right click. So that’s a bad pick. The most intuitive key is the `shift` key, isn't it?

**Comment by OmgImAlexis** [comment]
On OSX I'd use control which is in the same place as ctrl.

**Comment by ThibaultJanBeyer** [comment]
that is my point. Unfortunately, `ctrl` or `control` triggers a right click on OSX. I think you mean the command key `cmd`?
I’ll try with `shift`. I think that key is "free" (correct me if I’m wrong). It’s also the key used in native operating systems. Otherwise, I would have to detect the users operating system to switch between `ctrl` and `cmd`. Would like to avoid that.

**Comment by OmgImAlexis** [comment]
Oh yeah I meant <kbd>command</kbd> I was looking at the wrong part of my keyboard. lol

 Maybe detect `event.ctrlKey` and `event.metaKey`? They should be <kbd>ctrl</kbd> on Windows and <kbd>command</kbd> on OSX.

**Comment by ThibaultJanBeyer** [comment]
Unfortunately, it does not seem so…
`event.metaKey` (https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey):
> Note: On Macintosh keyboards, this is the command key (⌘). On Windows keyboards, this is the windows key (⊞).

And `event.ctrlKey` is the <kbd>ctrl</kbd> key on both os…

--- 

A solution is to make all four work the same: <kbd>shift</kbd>, <kbd>ctrl</kbd> & <kbd>command</kbd>/<kbd>windows</kbd>. Like that, windows/linux user can use <kbd>ctrl</kbd> (and the windows key) while mac will be able to use <kbd>command</kbd>. + all can use <kbd>shift</kbd> if needed.

The only downside is that like this a lot of keys get occupied, that’s why I would add a way to enable/disable them individually and all together in the config object.

How does that sound?

**Comment by OmgImAlexis** [comment]
Sounds good.

**Comment by OmgImAlexis** [comment]
I found a tiny library that helps map both <kbd>ctrl</kbd> and <kbd>command</kbd>.

https://github.com/timoxley/keycode

**Comment by ThibaultJanBeyer** [comment]
Done in v1.6.0
Related PR: #4 

## Modifiers:
<kbd>shift</kbd>, <kbd>ctrl</kbd> & <kbd>command</kbd>/<kbd>windows</kbd>
