### ISSUE TITLE
drag select freezes when edge is detected in area

### ISSUE THREAD

**Issue by woutergovaert** [ThibaultJanBeyer/DragSelect#22]
When drag select detects that it has run against the edge of the area in which it can operate it stops the selection of items. It would be nice that it would only limit the selection in the direction that is limited. For example when I drag up and it reaches the top area border I can't drag sideways anymore.

**Comment by ThibaultJanBeyer** [comment]
Hey @woutergovaert ,
thanks a lot for using the tool!

Indeed that is the current behavior because the tool only listens to the mouse movements inside the area. Changing that behavior without breaking things or rewriting a lot is probably quite difficult. I’m not sure if it’s worth the effort. Would you mind explaining exactly your usecase and why it is relevant?

Thanks in advance.

**Comment by ThibaultJanBeyer** [comment]
I’m closing this one since I did not hear back from you.
So I guess that it is not critical. I’ll still keep it in mind for further development.
