### ISSUE TITLE
area parameter with a svg node

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [ThibaultJanBeyer/DragSelect#26]
**Describe the bug**
When I set the `area` parameter with a SVG node, the selection doesn't work anymore

**To Reproduce**
Have such a tree

```html
<svg id="root">
    <rect class="selectable">
    <rect class="selectable">
</svg>
```

```js
new DragSelect({
    selectables: document.getElementsByClass("selectable"),
    area: document.getElementById("root")
})
```

**Expected behavior**
To be able to select node restricted to the #root element

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF nightly 
 - Version 63.0a1 (2018-06-27) (64-bit)

**Comment by ThibaultJanBeyer** [comment]
Hey Benjamin,

thanks for that very clean bug report.
Indeed that is a valid issue.

Do you feel confident enough to solve this? I would be very glad!
If not, just tell me and I’ll try to fix it.

Aside from that, how far did you advance with your first pull request?  (https://github.com/ThibaultJanBeyer/DragSelect/pull/25)
I think it is a huge improvement and would be very glad if it was mergeable. Let me know if you need any help with it.

Again, thanks a lot for actively contributing Benjamin, that means very much to me!

**Comment by ToastHammer09** [comment]
I've been playing around and I think I found the solution.

SVG won't display the selector box that is being generated within the SVG tags.

There is a property you can pass in to set a custom selector however you have to set its style with .ds-selector and change its parent tag to be relative in CSS.

I've modified your example to work:
```
new DragSelect({
    selectables: document.getElementsByClass("selectable"),
    area: document.getElementById("root"),
    selector: document.getElementById('selector') //add this line
})
```

```
<div style="position:relative;"> <!--container that is relative-->
    <svg id="root">
        <rect class="selectable">
        <rect class="selectable">
    </svg>
    <div id="selector" style="position: absolute; background: rgba(0, 0, 255, 0.1); border: 1px solid rgba(0, 0, 255, 0.45); display: none; "></div>
    <!--selector that is renderd outside the SVG and manualy added style (.ds-selector)-->
</div>
```

This has lead me onto these related bugs.
- I cant get SVG text and tspan to work correctly
- the area margin doesn't seem to be calculated when constraining the selector box to the area

**Comment by ThibaultJanBeyer** [comment]
Hey @ToastHammer09 thanks for providing the solution.

What you did is almost similar to what I would do. Actually I would recommend to just have the containing DIV as the Area like so:

```JavaScript
new DragSelect({
    selectables: document.getElementsByClass("selectable"),
    area: document.getElementById("area"),
});
```
```HTML
<div style="position:relative;" id="area">
    <svg id="root">
        <rect class="selectable">
        <rect class="selectable">
    </svg>
</div>
```

But that is just a monkey patch. It does not solve the issue with SVG properly. The problem is that HTML can not be written inside SVG. There is a solution using a [foreignobject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) wrapping the selector in the SVG. But I did not implement that because it only goes 1 level deep and actually works similarely to your solution. So again a monkey patch. If 1 level deep was enough, I could add a check to see if the area param is an SVG and if so, wrapp the selector inside that foreignobject. But the problem is that some users might want to restrict the selection to a certain group inside an svg and then that solution would fail again.

A proper solution would be to somehow check if the area is somehow inside an SVG and if so, draw the selector as an SVG tag (i.e. a `rect`). However that would also lead to the positioning algorythm that would have to be written from scratch for the rect element. So as you can see it’s a fix that would take quite some time.

> I cant get SVG text and tspan to work correctly
Would you mind adding a live example which demonstrates what that means?

> the area margin doesn't seem to be calculated when constraining the selector box to the area
That should be resolved when using the solution I provided above. Alternatively maybe `box-sizing: border-box;` might be sufficient
