### ISSUE TITLE
Are the Codepen examples supposed to be selectable and draggable or just selectable?

### ISSUE THREAD

**Issue by analizapandac** [ThibaultJanBeyer/DragSelect#32]
I'm looking at the Codepen examples because I'm interested but I'm confused on what is the expected behaviour of the selected elements when you try to drag them. 

Is it intentional that they are not moving when I try to drag them? Do I have to implement the re-positioning of the selected elements on drag or does the library does this by default?

**Comment by ThibaultJanBeyer** [comment]
Hey there @analizapandac thanks for your interest!

This is a selection plugin only.

You can combine it with my other plugin called dragNdrop to create your desired effect. This however is a bit more tricky. I got your request once some time ago. I started writing a combination of both which is not open publicly yet tho'. As you are now the second person with that specific request, I'll try to speed up that development. There are open issues for that in both repos (see https://github.com/ThibaultJanBeyer/DragSelect/issues/24) I'll close this issue here. Feel free to give #24 a +1 from your side. Thanks again, -T
