### ISSUE TITLE
Add text-editor-like selection mode.

### ISSUE THREAD

**Issue by paulrosen** [ThibaultJanBeyer/DragSelect#41]
**Is your feature request related to a problem? Please describe.**
I have a set of buttons arranged in rows, and intended to be traversed just like reading text: That is, first row, left to right, second row, left to right, etc. The selection should include all the buttons between those two, but they won't be covered by a rectangle.

**Describe the solution you'd like**
When clicking on the first button, it selects it and when dragging around, instead of a rectangle, I'd like to highlight all of the buttons consecutively to the end.

**Describe alternatives you've considered**
I thought I could just keep track of it myself, but I don't think I know where the cursor currently is. I'm looking at onElementSelect, but that isn't necessarily it.

**Additional context**
First, I really love this library! It works well, and easily and it looks good out of the box! I wish that I were selecting an area instead of text-like data.

So, imagine that you are selecting part of a paragraph of text. That's what I'd like to do.

**Comment by ThibaultJanBeyer** [comment]
Hi @paulrosen thanks for using the tool and thank you for this issue.

I'm not sure if I understood your request correctly could you please provide a mocked example?

If I assume that you want to select elements without showing the selection, you can already do that. Have a look at the documentation: https://thibaultjanbeyer.github.io/DragSelect/DragSelect.html . There is a parameter called `customStyles` which will remove all styles applied by default to the selection. Now you won't see the selection rectangle anymore and you can handle the selected elements yourself the way you want it to look like.

Let me know if that helps, otherwise I would probably need more explanation

**Comment by paulrosen** [comment]
I thought about this more and started experimenting, so I know what I want now, I think. It looks like I can get what I want using:
```
dragSelect = new DragSelect({
  selectables: etc...,
  onElementSelect: onElementSelect,
});

onElementSelect() {
  console.log(dragSelect._initialCursorPos, dragSelect._newCursorPos);
},
```
I can then figure out what region was selected first and which region was selected most recently and do my own logic.

So, it is a little sloppy using internal variables of DragSelect, but that will allow me to evaluate my feature.

It would be nice to return those two coordinates "officially".

**Comment by paulrosen** [comment]
A little more of an update: I have a working version in my code by using `onDragMove` and calculating which button `dragSelect._initialCursorPos` and `dragSelect._newCursorPos` are under. That is working great. I was thinking it might be useful to add that as its own callback, though. Something like:
```
dragSelect = new DragSelect({
  onEndpointsChange: function (startButton, currentButton) {
    // startButton is the element that the user originally clicked on.
    // currentButton is the element that the mouse is currently over.
  }
});
```
I pretty much have that code already if you think it would be useful to contribute back.

**Comment by ThibaultJanBeyer** [comment]
Hey there, thanks for the updates. Do you mind sharing your example so I can understand how you are using the tool and how to help you. Maybe also share how you are calculating the `onDragMove` please maybe there is a better way already.
Thank you

**Comment by paulrosen** [comment]
My code isn't particularly separable from the app, but here are some snippets that should give you an idea. I'm sure what I'm doing is not at all efficient, but it's fast enough:
```
// My button targets are numbered consecutively from zero, from left to right, in rows. The size of each of them is in the array measureSizes.

// This translates an (x,y) coordinate into an index. If dragging outside of a button, then it returns -1.
// Note that it takes scrolling into account.
findMeasureNumber(pos) {
	const x = pos.x + this.dragSelect._initialScroll.x;
	const y = pos.y + this.dragSelect._initialScroll.y;
	const measure =  this.measureSizes.find(m => {
		return m.left <= x && m.top <= y && m.right >= x && m.bottom >= y;
	});
	if (measure)
		return measure.index;
	else return -1;
},

// This is the callback from DragSelect.
// setRubberBand adds the class "rubber-band" to the measures inside the range.
moveCallback() {
	this.setRubberBand(this.findMeasureNumber(this.dragSelect._initialCursorPos),
		this.findMeasureNumber(this.dragSelect._newCursorPos));
},

// This is the callback from DragSelect
// setSelection adds the class "selected" to the measures inside the range.
// If the user is not over a button when releasing the mouse, then the last button they were over is used.
finishedDragging(els) {
	const initialMeasure = this.findMeasureNumber(this.dragSelect._initialCursorPos);
	let finalMeasure = this.findMeasureNumber(this.dragSelect._newCursorPos);
	if (finalMeasure === -1)
		finalMeasure = this.lastValidEnd;
	this.setMeasureSelectionStart(Math.min(initialMeasure, finalMeasure));
	this.setMeasureSelectionEnd(Math.max(initialMeasure, finalMeasure));
	this.setSelection();
},
```

**Comment by paulrosen** [comment]
I found two bugs in the above code so far:
1) If the area auto scrolls while dragging, the _initialScroll value isn't the right one to use to calculate what item I'm on.
2) When clicking with the keyboard instead of the mouse, the _initialCursorPos value isn't set.

**Comment by ThibaultJanBeyer** [comment]
It’s really hard to tell how to help you because I still don’t understand what you are trying to do.

One thing tho’ you’re using private methods a lot. It’s suggested to use non-private methods (you can differenciate them with the underscore. Private methods are prefixed with `_` non-private don’t) this is because there is no long-term support for private methods and they might change at any time.

I strongly advise to have a look at the documentation: https://thibaultjanbeyer.github.io/DragSelect/DragSelect.html

For example instead of getting `this.dragSelect._initialCursorPost` use `getInitialCursorPosition` and instead of `this.dragSelect._newCursorPos` use `getCurrentCursorPosition`. There is no getter for the `_initialScroll` yet.

> 1. If the area auto scrolls while dragging, the _initialScroll value isn't the right one to use to calculate what item I'm on.

So since using `_initialScroll` is not supported, I won’t consider point 1 as a bug.

> 2. When clicking with the keyboard instead of the mouse, the _initialCursorPos value isn't set.

`_initialCursorPos` should be `{ x: 0, y: 0 }` as long as there has not been any cursor interaction. (see: https://thibaultjanbeyer.github.io/DragSelect/DragSelect.js.html#line53). This is expected.

You could probably provide a working mock of what you are trying to achieve as a gif or screenshots or maybe even a codepen, so that I understand it. Seems as if it is hard to explain in written text.

On first sight it sounds as if you are heavily mis-using the tool for something that it was not build for :/

Maybe if you tell me what could make life simpler for your use case we can discuss about adding it.

As it seems you found some kind of solution so for now I will close this issue and re-open as soon as I understand how to solve that very specific problem.

**Comment by paulrosen** [comment]
Sorry, my work around did the trick so I dropped the ball on this. Here is what I came up with:

![measure-selection](https://user-images.githubusercontent.com/69818/61883388-5b4d5e00-aec8-11e9-9379-c0e4c2a5570a.gif)

There are invisible buttons on top of each measure. You'll notice that the selection is not rectangular.

**Comment by ThibaultJanBeyer** [comment]
Ah, I see.
For that it seems to me that you just need to override/hide the CSS styles with the parameter called `customStyles` which will remove all styles applied by default to the selection, so you can set your own in CSS. No need to touch any internals of the tool.
It looks very nice btw. :)
