### ISSUE TITLE
selectables must accept selection string\array of strings 

### ISSUE THREAD

**Issue by deser** [ThibaultJanBeyer/DragSelect#49]
**Is your feature request related to a problem? Please describe.**
I'm having app which adds new elements on selectable area. To not-reinitialize selection every time it would be nice to pass to DragSelect just selectors I want to be selected

**Describe the solution you'd like**
selectables: ['.items']

**Comment by ThibaultJanBeyer** [comment]
Dear @deser, first, thank you for using the tool!
Sorry for the late response, due to corona everything was delayed.

Now I don't really understand the feature request, would you mind to clarify?
You can already pass the items you want using `selectables: ['.items']` ? That would work.
If you want to add more later on there is `addSelectables()`.

Have a look at [the docs](https://thibaultjanbeyer.github.io/DragSelect/DragSelect.html#addSelectables).

Does that help?

**Comment by ThibaultJanBeyer** [comment]
I'm closing it for now, if that's not what you were talking about, let me know and we can re-open the issue ticket :)
