### ISSUE TITLE
Uncaught TypeError in Chrome

### ISSUE THREAD

**Issue by bxchang04** [ThibaultJanBeyer/DragSelect#51]
**Describe the bug**
In Chrome, console reads "ds.js:226 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at DragSelect._handleArea (ds.js:226)
    at new DragSelect (ds.js:207)
    at dragSelect.js:1
_handleArea @ ds.js:226
DragSelect @ ds.js:207
(anonymous) @ dragSelect.js:1"

...for both CodePen examples when running them locally on my machine.

**To Reproduce**
1. Go to https://github.com/bxchang04/dragSelectTest
2. Open test.html
3. View console in browser (I'm using Chrome Version 80.0.3987.149 (Official Build) (64-bit))

**Expected behavior**
Should output like the two codePens (https://codepen.io/ThibaultJanBeyer/pen/prpwYG/ and https://codepen.io/ThibaultJanBeyer/pen/Nvobgq/) in your gitHub. However, I just get all 6 items in the top left stacked on top of each other. The top one is selectable on click, but drag select does not work.

**Screenshots**
![image](https://user-images.githubusercontent.com/42091866/78507944-3268b280-7751-11ea-87ee-9646fec38d9b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: 80.0.3987.149 (Official Build) (64-bit))

**Comment by bxchang04** [comment]
FYI I found out this issue is caused when DragSelect is installed via NPM and also called locally in my HTML file using <script>js/ds.min.js</script>. I chose to use the non-minified version so that the console message would show me the correct line that was causing this error.

**Comment by bxchang04** [comment]
I've updated my repo. To reproduce, please download the project, install DS via npm, then open "test1.html"

**Comment by ThibaultJanBeyer** [comment]
Dear @bxchang04,

thank you for using DragSelect, that's great! 💪 

I've just opened your example and it seems to work fine?
See [this screen capture video](https://we.tl/t-5QK1idFe6B) (available for 1 week from now)

However, I noticed that you had some very basic typos/issues in your code:

- You have to add the DragSelect script first *before* loading the scripts with your own code. Otherwise, it would not be initiated.
- It has to be `<script src="js/ds.js"></script>` *not* `<script>js/ds.js</script>` because what you write within the brackets is the code that gets executed, if you want to load a script file it has to go in the `src` property.

I hope that helps. If not please write again, and maybe share your codepen instead of the github repo. Thanks

**Comment by bxchang04** [comment]
Thanks! Fixing the typos did the trick. Pardon me as I am very new to web dev.

However for some reason the CSS isn't working. My boxes are still overlapping and not in random positions. Any idea what's causing this?

https://codepen.io/bxchang04/pen/GRJbVyq
