### ISSUE TITLE
Drag select autoscroll keeps scrolling past area height

### ISSUE THREAD

**Issue by owenfar** [ThibaultJanBeyer/DragSelect#63]
**Describe the bug**
As discussed in https://github.com/ThibaultJanBeyer/DragSelect/pull/59#issuecomment-722656112 .. Drag select autoscroll keeps scrolling past the maximum area height. You can see this clearly below:

**Screenshots**
![autoscroll-bug](https://user-images.githubusercontent.com/25148235/98442419-c6926200-2104-11eb-9ab9-430ba1154914.gif)

**To Reproduce**
Create a scrollable div as a selectable area, and include multiple selectables so that a drag select triggers an autoscroll event (make area scrollable). When the cursor is close/near to the edge of the area, the scroll goes past the scrollable height indefinitely.

**Expected behavior**
Once the scroll reaches the bottom (end of scrollable height), the autoscroll event should stop.

**Desktop (please complete the following information):**
 - OS: latest macOS
 - Browser: Chrome
 - Version: latest version

**Additional context**
If anyone knows where this can be fixed or point me to the right part in code, I can try to find a fix myself & create a PR.

Thank you

**Comment by ThibaultJanBeyer** [comment]
Dear @owenfar thanks again for pointing this out 👍 

If you want to fix it yourself I'd probably go like this:
- check how to get the max scroll of the area
- check how to make sure that the max scroll is reliable
- check on how to identify where either the cursor or the selection is
- if cursor/selection is above max scroll, clear the `this._autoScrollInterval` within `_setScrollState`
 
If you don't feel confident fixing this, no worries.
Maybe @slinhart do you have time to follow up on this since it's kinda related to #59?
Otherwise, let me know and I'll have a look as soon as I find time :)

**Comment by slinhart** [comment]
Hey @ThibaultJanBeyer I can likely take a look at this sometime this week. I can't say I've noticed this issue yet though; is it reproducible with the testing environment brought up with `npm start`?

**Comment by slinhart** [comment]
Never mind, I see the issue 👍

**Comment by slinhart** [comment]
The cause of the issue seems to be that the selector element is being rendered beyond the bounds of the container, causing the `area` to have it's scrollHeight/scrollWidth expanded. Notice that for this issue to be reproduced you have to drag the cursor outside of the scrollable container.
Perhaps there needs to be a check in _updatePos to make sure the the selector won't be rendered in a what that expands the area. But I wanted to ask you @ThibaultJanBeyer your thoughts on how to approach this.

**Comment by ThibaultJanBeyer** [comment]
We may just stop the `_autoScrollInterval` if it expands the area in case that's easier? Otherwise yeah probably in _updatePos. Just have to make sure that it works in all occasions :O

**Comment by owenfar** [comment]
Hey @slinhart & @ThibaultJanBeyer, just to leave my thoughts. I think it would be great if when a dragSelect happens inside such an area, we can keep it scrolling all the way down even when the mouse is outside - this is the same behavior we currently have on our OS. Is it difficult (since we're on this issue) to make the dragSelect stick to the mouse position, even when outside the area, but have it in an overflow state set to hidden, so to have something like this:

![example](https://user-images.githubusercontent.com/25148235/98594258-b29d5a80-22d4-11eb-96fb-62014879325c.png)

I don't want to complicate, so just ignore otherwise - this is perhaps more of an improvement, but it is related.

Looking forward & thanks a lot @slinhart too for your time to look into this update.

**Comment by ThibaultJanBeyer** [comment]
That might actually be impossible in the browser :/

**Comment by ThibaultJanBeyer** [comment]
I was thinking about this. Maaayybe, we could try instead of placing the selection element inside of the area, we'd create a new area with `overflow hidden` that has the same sizes and position as the area and place the selection in there but still handle it as if it was inside of the provided area. Not sure if that's feasible tho'. It's definitively not easy and in this case, it's more something for a v2 imo as it might be breaking. I'll also have a look…

**Comment by owenfar** [comment]
That sounds great @ThibaultJanBeyer. I'm already very happy with the new updates, and I will be looking forward for v2 whenever it comes :) Thank you

**Comment by owenfar** [comment]
Hello @ThibaultJanBeyer, hope all is well.

I finally had the time to update to v2, it's really great to see all the bugs & enhancements in this version.

I know this isn't something you would want to hear though, because this must have taken quite some time for you to accomplish as is, but I'm afraid it breaks some other things.

I see that all ds-selector areas have been moved into the main body node, and you're keeping states for multiple specific dragSelect areas to hide & show the right one accordingly. The problem now is managing z-index :/ Since all ds-selector areas are under one element at the top of the node tree, it's impossible to keep a "window" above another dragSelect area, as we do not have control of the z-index anymore. One example would be a "window" above a "desktop".. the desktop ds-selector would go above the whole window as it is now:

![ds-over-window](https://user-images.githubusercontent.com/25148235/154266531-ee847b34-97d9-46ee-af3e-9ca1bd2829e2.jpg)

This separation makes the whole process a bit tricky to handle, and I'm starting to wonder whether this was actually the best solution. Unfortunately, because of this issue, I again will have to revert back to v1.

There are some things I imagine would be the perfect scenario for the ds-selector:
1. That we have only one ds-selector globally, and it is moved according to the current clicked position if a ds-area exists - I know this must create other complexities, it's more for the sake of less-is-better.
2. Re-accomplish _this_ issue by determining the max-height, max-width of the current area and stop the scrolling process once the max scroll position is reached - My best guess regarding how we would tackle the selector going outside the window would be to follow the cursor on the whole viewport, instead of just the specific area?

I would love to dedicate some time on this library, and will try pinging current co. if we can spare some time. Otherwise if you think some kind of sponsorship could help let me know as well :) 

Thank you and let me know if you think this should be opened as an issue.

**Comment by ThibaultJanBeyer** [comment]
Hi, @owenfar thanks for this feedback, can you please open a new issue regarding this? Since it's not really related to this issue. And let's discuss it there then. Thank you!

Yes, a sponsorship would help **_for sure_**! Currently, this is my lowest priority and just a hobby, since I get "paid" exactly 1$/month from my GitHub sponsors. This does not even cover my "GitHub pro" subscription. If my open source work would generate an income, I could spend less time at my day job and more time on open-source :)

If you are a company and profit from this library, please think about supporting the work via GitHub Sponsors: https://github.com/sponsors/ThibaultJanBeyer.

As you can see there are tiers that allow me to put time dedicated on open source or your issues.

Otherwise, life and day-job will always have priority as you can see :)

**Comment by owenfar** [comment]
Hello @ThibaultJanBeyer, will open a new issue about this now, thank you for reaching back about this.

We don't use this on any production software, actually it's more of a pet project I'm building on my own. I would be more than happy to if I had the finances, but so far nothing. I will as promised last year, try to dedicate some time hopefully soon to help with the library.

Thanks once again.

**Comment by ThibaultJanBeyer** [comment]
Thank you for being a great person, I hope your pet project will be successful 🤗
