### ISSUE TITLE
DragSelect overrides default behavior

### ISSUE THREAD

**Issue by divdax** [ThibaultJanBeyer/DragSelect#8]
Hey,

If i use DragSelect to select some div elements links inside this div doesn't work anymore.
Maybe there should be a drag threshold?

**Comment by zappzerapp** [comment]
I don't know how useful this is for you, but my little workaround is something like this:

`onElementSelect: function (element) {
    if ($('.ds-selector').height() === 0 && $('.ds-selector').width() === 0) {
        $(element).click();
    }
},`

**Comment by zappzerapp** [comment]
I did a little workaround for solving this issue:

CSS:
```
.ds-selector {
    display: none!important;
}

.ds-selector.visible {
    display: block!important;
}
```

JS:
```
var ds = new DragSelect({ ... });

ds.area.addEventListener('mousemove', function () {
    if ($(ds.selector).height() > 5 || $(ds.selector).width() > 5) {
        $(ds.selector).addClass('visible');
    }
});

ds.area.addEventListener('mouseup', function () {
    $(ds.selector).removeClass('visible');
});
```

**Comment by ThibaultJanBeyer** [comment]
Hello @divdax. Thanks for opening an issue, I was on holidays the last days. Will have a look into this the upcoming days.
Would you be so kind to create an example of your issue? (use codepen for example) That would help a lot!
For now, thanks @zappzerapp for finding a quick fix 👍

**Comment by ThibaultJanBeyer** [comment]
@divdax so I tried to reproduce your issue. I am not sure if I did it correctly but it seems that the behaviour you’re describing of links not working inside the draggable elements is not due to DragSelect but to the fact that you have links inside of <button> tags... Is that correct?

I added some code to address this issue, see [commit 096d4aa](https://github.com/ThibaultJanBeyer/DragSelect/commit/096d4aae7fb93d549f3e6fcf24805c7c22b31864). Basically, it re-hides the selector until it is moved. Also, I added `pointer-events: none;` to the selector as default styles. This should solve your issue… Please try the newest version (1.7.10) and let me know.

__
FYI: the thing is links inside buttons is that this is incorrect html (see "[the button element](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element)": Content model: _Phrasing content, but there must be no interactive content descendant_). While it will still work in Chrome and other browers, it might not work in older browsers, you will have to use div tags or similar instead of buttons (keep in mind that it will break accessibility tho’).
