### ISSUE TITLE
Similar to setSelectables, please provide a setArea

### ISSUE THREAD

**Issue by diomedtmc** [ThibaultJanBeyer/DragSelect#95]
**Is your feature request related to a problem? Please describe.**
My entire selectable area might change, not just the selectables within it.  Since I cannot correctly tear down the DragSelect DOM (at the moment), I would like to manage this through singletons; however, if I remove my scrollable area from the DOM, I can't reset the scrollable area on the Singleton instance.

**Describe the solution you'd like**
A setArea method, similar to setSelectables.

**Describe alternatives you've considered**
I tear down the DOM myself when I need to.  I manage a singleton lifecycle as much as possible between components/screens.

**Additional context**
My work is generally within React, and is component focused.

**Comment by diomedtmc** [comment]
If I can get in there and work on the teardown, I'll have a play at this one too.  Thank you @ThibaultJanBeyer !

**Comment by ThibaultJanBeyer** [comment]
To be honest, you can use multiple instances of `DragSelect`, one for each area you have. If it changes you can teardown DragSelect by using `.stop`.

Let me know if that's not sufficient or if you have a solution PR and we can re-open this issue. 

Cheers :)

**Comment by Ptival** [comment]
I think I may have a use case where `setArea` would be very useful, but I'm still mentally working through it (and discovered this library only hours  ago), so let's see what people think.

My use case is creating a parent React component that will contain a bunch of other React components that I intend to be selectable/draggable.

The problem is, because the parent component is only mounted later, you want to put the constructor call in the "mounted" callback, but that means you don't get to pass the `DragSelect` object to your children at construction, and instead need to delay everything.

e.g. with `setArea` I think I'd do something like:

```typescript
const MyParentComponent = props => {

    const dragSelect = new DragSelect() // no area!

    React.useEffect(() => {
        // now that the component is mounted, it makes sense to track its area
        dragSelect.setArea(selfRef.current) // ignoring the `null` for this example
    })

    return (
        <div ref={selfRef}>
            <SubComponent1 dragSelect={dragSelect} /> // on mount, it will `dragSelect.addSelectables([self])`
            <SubComponent2 dragSelect={dragSelect} />
        </div>
    )
}
```

Without `setArea`, things become... painful? I think I can get away with a promise like so:


```typescript
const MyParentComponent = props => {

    const dragSelect = new Promise(resolve => {
        React.useEffect(() => {
            const dragSelect = new DragSelect({ area: selfRef.current }) // still ignoring the `null`
            resolve(dragSelect)
        })
    })

    return (
        <div ref={selfRef}>
            <SubComponent1 dragSelect={dragSelect} /> // now I'll have to wait for being mounted and the promise resolving
            <SubComponent2 dragSelect={dragSelect} />
        </div>
    )
}
```

Doesn't look too awful, but it's just a bit of extra work that could be skipped. But I don't know if `setArea` is complex to implement, so I understand not wanting to support it. :-) Just a data point.

Let me know if you have a better solution!

**Comment by ThibaultJanBeyer** [comment]
Can you work with State? something like this?

```
const MyParentComponent = props => {
    const [dragSelect, setDragSelect] = useState(new DragSelect())

    React.useEffect(() => {
       dragSelect.stop()
        // now that the component is mounted, it makes sense to track its area
       setDragSelect(new DragSelect({ area: selfRef.current }))
    }, [])

    return (
        <div ref={selfRef}>
            <SubComponent1 dragSelect={dragSelect} /> // on mount, it will `dragSelect.addSelectables([self])`
            <SubComponent2 dragSelect={dragSelect} />
        </div>
    )
}
```

Does that make sense? Feel free to look into adding a `setArea` to the library btw. :)

**Comment by Ptival** [comment]
I'm trying this today and it brings the engine to a halt within seconds of dragging anything.

Not sure why, during my first drag everything is normal, but if I release the selectable, and then drag it again, now I not only see my component move, but also the blue box indicating box selection, and it is no longer half transparent but opaque, seemingly indicating that multiple such boxes are being drawn.

So it seems like either `stop()` is not enough cleanup, or I'm doing something incorrect elsewhere.

**Comment by ThibaultJanBeyer** [comment]
This is now possible [see docs](https://github.com/ThibaultJanBeyer/DragSelect#post-initialization-setting-updates):

```JavaScript
ds.setSettings({ area: << new are element >> })
```
